import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // 10 Cases
  const casesData = [
    {
      entryDate: new Date('2025-09-05T00:00:00Z'),
      entryNumber: '336-Վ/23',
      caseNumber: 'ԱՎԴ1/0007/02/25',
      judge: 'Գ․Հարությունյան',
      plaintiff: 'Հայ Էկոնոմ Բանկ',
      defendant: 'Արսեն Գրիգորյան',
      investigatedAddress: 'Արարատի մարզ, Սասունի փողոց 26',
      propertyType: 'Հող, Համալիր',
      isPaid: false,
      price: 80000,
      payment_type: 'transfer',
      status: 'waiting',
      closed_at: null,
      caseType: 'Չափագրում',
      assignedEmployee: { connect: { id: 1 } },
    },
    {
      entryDate: new Date('2025-09-05T01:00:00Z'),
      entryNumber: '337-Վ/23',
      caseNumber: 'ԱՎԴ1/0008/02/25',
      judge: 'Ս․Ավետիսյան',
      plaintiff: 'Հայաստանի Զարգացման Բանկ',
      defendant: 'Մարինե Սարգսյան',
      investigatedAddress: 'Երևան, Թբիլիսյան 12',
      propertyType: 'Շենք',
      isPaid: false,
      price: 120000,
      payment_type: 'cash',
      status: 'in_progress',
      closed_at: null,
      caseType: 'Չափագրում',
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2025-09-05T02:00:00Z'),
      entryNumber: '338-Վ/23',
      caseNumber: 'ԱՎԴ1/0009/02/25',
      judge: 'Մ․Մելիքյան',
      plaintiff: 'ԱՐԴԲԱՆԿ',
      defendant: 'Դավիթ Հովհաննիսյան',
      investigatedAddress: 'Գյումրի, Լերմոնտովի 15',
      propertyType: 'Բնակարան',
      isPaid: false,
      price: 95000,
      payment_type: 'transfer',
      status: 'waiting',
      closed_at: null,
      caseType: 'Չափագրում',
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2025-09-05T03:00:00Z'),
      entryNumber: '339-Վ/23',
      caseNumber: 'ԱՎԴ1/0010/02/25',
      judge: 'Ռ․Խաչատրյան',
      plaintiff: 'Արդշինբանկ',
      defendant: 'Միքայել Պետրոսյան',
      investigatedAddress: 'Վանաձոր, Բաղրամյան 20',
      propertyType: 'Հող',
      isPaid: false,
      price: 110000,
      payment_type: 'court',
      status: 'completed',
      closed_at: null,
      caseType: 'Չափագրում',
      assignedEmployee: { connect: { id: 4 } },
    },
    {
      entryDate: new Date('2025-09-05T04:00:00Z'),
      entryNumber: '340-Վ/23',
      caseNumber: 'ԱՎԴ1/0011/02/25',
      judge: 'Ա․Հովսեփյան',
      plaintiff: 'Երևան Կենտրոնական Բանկ',
      defendant: 'Լիլիթ Հովհաննիսյան',
      investigatedAddress: 'Երևան, Աբովյան 5',
      propertyType: 'Բնակարան',
      isPaid: false,
      price: 105000,
      payment_type: 'transfer',
      status: 'waiting',
      closed_at: null,
      caseType: 'Չափագրում',
      assignedEmployee: { connect: { id: 5 } },
    },
    {
      entryDate: new Date('2025-09-05T05:00:00Z'),
      entryNumber: '341-Վ/23',
      caseNumber: 'ԱՎԴ1/0012/02/25',
      judge: 'Մ․Սարգսյան',
      plaintiff: 'Տիգրան Մեծ Բանկ',
      defendant: 'Աշոտ Միքայելյան',
      investigatedAddress: 'Երևան, Մալաթիա 3',
      propertyType: 'Շենք',
      isPaid: false,
      price: 75000,
      payment_type: 'cash',
      status: 'in_progress',
      closed_at: null,
      caseType: 'Չափագրում',
      assignedEmployee: { connect: { id: 6 } },
    },
    {
      entryDate: new Date('2025-09-05T06:00:00Z'),
      entryNumber: '342-Վ/23',
      caseNumber: 'ԱՎԴ1/0013/02/25',
      judge: 'Գ․Հարությունյան',
      plaintiff: 'Հայ Էկոնոմ Բանկ',
      defendant: 'Նարեկ Սարգսյան',
      investigatedAddress: 'Արարատի մարզ, Մասիս 18',
      propertyType: 'Հող',
      isPaid: false,
      price: 88000,
      payment_type: 'transfer',
      status: 'waiting',
      closed_at: null,
      caseType: 'Չափագրում',
      assignedEmployee: { connect: { id: 7 } },
    },
    {
      entryDate: new Date('2025-09-05T07:00:00Z'),
      entryNumber: '343-Վ/23',
      caseNumber: 'ԱՎԴ1/0014/02/25',
      judge: 'Ս․Ավետիսյան',
      plaintiff: 'ԱՐԴԲԱՆԿ',
      defendant: 'Անի Գրիգորյան',
      investigatedAddress: 'Գյումրի, Խորենացի 10',
      propertyType: 'Բնակարան',
      isPaid: false,
      price: 96000,
      payment_type: 'court',
      status: 'closed',
      closed_at: new Date('2025-09-10T12:00:00Z'),
      caseType: 'Չափագրում',
      assignedEmployee: { connect: { id: 8 } },
    },
    {
      entryDate: new Date('2025-09-05T08:00:00Z'),
      entryNumber: '344-Վ/23',
      caseNumber: 'ԱՎԴ1/0015/02/25',
      judge: 'Մ․Մելիքյան',
      plaintiff: 'Տիգրան Մեծ Բանկ',
      defendant: 'Մհեր Հովհաննիսյան',
      investigatedAddress: 'Վանաձոր, Տերյան 22',
      propertyType: 'Շենք',
      isPaid: false,
      price: 105000,
      payment_type: 'transfer',
      status: 'waiting',
      closed_at: null,
      caseType: 'Չափագրում',
      assignedEmployee: { connect: { id: 9 } },
    },
    {
      entryDate: new Date('2025-09-05T09:00:00Z'),
      entryNumber: '345-Վ/23',
      caseNumber: 'ԱՎԴ1/0016/02/25',
      judge: 'Ռ․Խաչատրյան',
      plaintiff: 'Հայաստանի Զարգացման Բանկ',
      defendant: 'Սոֆյա Գրիգորյան',
      investigatedAddress: 'Երևան, Կոմիտաս 12',
      propertyType: 'Հող',
      isPaid: false,
      price: 99000,
      payment_type: 'cash',
      status: 'in_progress',
      closed_at: null,
      caseType: 'Չափագրում',
      assignedEmployee: { connect: { id: 10 } },
    },
  ]

  for (const caseItem of casesData) {
    await prisma.case.create({ data: caseItem })
  }

  console.log('Cases seeded.')
}

main()
  .catch((e) => console.error(e))
  .finally(async () => {
    await prisma.$disconnect()
  })
