const cases = [
  {
    entryDate: new Date('2023-01-05T00:00:00Z'),
    entryNumber: '101-Վ/23',
    caseNumber: 'ԱՎԴ1/0001/01/23',
    judge: 'Ա. Սարգսյան',
    plaintiff: 'ԱրմՍտրոյԲանկ',
    defendant: 'Գևորգ Մանուկյան',
    investigatedAddress: 'Երևան, Նալբանդյան 12',
    propertyType: 'Բնակարան',
    caseType: 'Գրանցում',
    isPaid: true,
    price: 65000,
    payment_type: 'transfer',
    status: 'closed',
    closed_at: new Date('2023-02-18T00:00:00Z'),
    assignedEmployee: { connect: { id: 2 } }
  },
  {
    entryDate: new Date('2023-03-10T00:00:00Z'),
    entryNumber: '102-Վ/23',
    caseNumber: 'ԱՎԴ1/0002/03/23',
    judge: 'Լ. Հարությունյան',
    plaintiff: 'Ազատություն Բանկ',
    defendant: 'Մարիամ Հարությունյան',
    investigatedAddress: 'Երևան, Գարեգին Նժդեհ 8',
    propertyType: 'Տուն',
    caseType: 'Գրանցում',
    isPaid: true,
    price: 120000,
    payment_type: 'cash',
    status: 'closed',
    closed_at: new Date('2023-04-22T00:00:00Z'),
    assignedEmployee: { connect: { id: 3 } }
  },
  {
    entryDate: new Date('2023-05-12T00:00:00Z'),
    entryNumber: '103-Վ/23',
    caseNumber: 'ԱՎԴ1/0003/05/23',
    judge: 'Ս. Թորոսյան',
    plaintiff: 'ՎՏԲ Հայաստան Բանկ',
    defendant: 'Հրաչիկ Սիմոնյան',
    investigatedAddress: 'Երևան, Մաշտոց 45',
    propertyType: 'Հողատարածք',
    caseType: 'Գրանցում',
    isPaid: true,
    price: 45000,
    payment_type: 'transfer',
    status: 'closed',
    closed_at: new Date('2023-06-30T00:00:00Z'),
    assignedEmployee: { connect: { id: 4 } }
  },
  {
    entryDate: new Date('2023-07-15T00:00:00Z'),
    entryNumber: '104-Վ/23',
    caseNumber: 'ԱՎԴ1/0004/07/23',
    judge: 'Մ. Կարապետյան',
    plaintiff: 'ԱրմՍտրոյԲանկ',
    defendant: 'Արմեն Ղազարյան',
    investigatedAddress: 'Երևան, Աբովյան 18',
    propertyType: 'Ավտոմեքենա',
    caseType: 'Վաճառք',
    isPaid: true,
    price: 30000,
    payment_type: 'cash',
    status: 'closed',
    closed_at: new Date('2023-08-10T00:00:00Z'),
    assignedEmployee: { connect: { id: 5 } }
  },
  {
    entryDate: new Date('2023-09-02T00:00:00Z'),
    entryNumber: '105-Վ/23',
    caseNumber: 'ԱՎԴ1/0005/09/23',
    judge: 'Գ. Հովհաննիսյան',
    plaintiff: 'Ինեկոբանկ',
    defendant: 'Արփինե Մելիքյան',
    investigatedAddress: 'Երևան, Դավիթ Բեկ 23',
    propertyType: 'Գույք',
    caseType: 'Վաճառք',
    isPaid: true,
    price: 15000,
    payment_type: 'transfer',
    status: 'closed',
    closed_at: new Date('2023-10-05T00:00:00Z'),
    assignedEmployee: { connect: { id: 6 } }
  },
  {
    entryDate: new Date('2024-01-10T00:00:00Z'),
    entryNumber: '106-Վ/24',
    caseNumber: 'ԱՎԴ1/0006/01/24',
    judge: 'Ա. Սարգսյան',
    plaintiff: 'Ազատություն Բանկ',
    defendant: 'Արմենիկ Հակոբյան',
    investigatedAddress: 'Երևան, Մաշտոցի պողոտա 78',
    propertyType: 'Բնակարան',
    caseType: 'Վաճառք',
    isPaid: true,
    price: 70000,
    payment_type: 'court',
    status: 'closed',
    closed_at: new Date('2024-02-12T00:00:00Z'),
    assignedEmployee: { connect: { id: 2 } }
  },
  {
    entryDate: new Date('2024-03-15T00:00:00Z'),
    entryNumber: '107-Վ/24',
    caseNumber: 'ԱՎԴ1/0007/03/24',
    judge: 'Լ. Հարությունյան',
    plaintiff: 'ԱրմՍտրոյԲանկ',
    defendant: 'Գագիկ Ավետիսյան',
    investigatedAddress: 'Երևան, Նալբանդյան 34',
    propertyType: 'Տուն',
    caseType: 'Գրանցում',
    isPaid: true,
    price: 135000,
    payment_type: 'transfer',
    status: 'closed',
    closed_at: new Date('2024-04-20T00:00:00Z'),
    assignedEmployee: { connect: { id: 3 } }
  },
  {
    entryDate: new Date('2024-05-20T00:00:00Z'),
    entryNumber: '108-Վ/24',
    caseNumber: 'ԱՎԴ1/0008/05/24',
    judge: 'Ս. Թորոսյան',
    plaintiff: 'ՎՏԲ Հայաստան Բանկ',
    defendant: 'Մարիամ Գրիգորյան',
    investigatedAddress: 'Երևան, Խանջյան 9',
    propertyType: 'Հողատարածք',
    caseType: 'Գրանցում',
    isPaid: true,
    price: 60000,
    payment_type: 'cash',
    status: 'closed',
    closed_at: new Date('2024-06-25T00:00:00Z'),
    assignedEmployee: { connect: { id: 4 } }
  },
  {
    entryDate: new Date('2024-07-12T00:00:00Z'),
    entryNumber: '109-Վ/24',
    caseNumber: 'ԱՎԴ1/0009/07/24',
    judge: 'Մ. Կարապետյան',
    plaintiff: 'Ինեկոբանկ',
    defendant: 'Հասմիկ Սարգսյան',
    investigatedAddress: 'Երևան, Տերյան 5',
    propertyType: 'Ավտոմեքենա',
    caseType: 'Վաճառք',
    isPaid: true,
    price: 25000,
    payment_type: 'cash',
    status: 'closed',
    closed_at: new Date('2024-08-10T00:00:00Z'),
    assignedEmployee: { connect: { id: 5 } }
  },
  {
    entryDate: new Date('2024-09-05T00:00:00Z'),
    entryNumber: '110-Վ/24',
    caseNumber: 'ԱՎԴ1/0010/09/24',
    judge: 'Գ. Հովհաննիսյան',
    plaintiff: 'Ազատություն Բանկ',
    defendant: 'Արմեն Մարտիրոսյան',
    investigatedAddress: 'Երևան, Բաղրամյան 11',
    propertyType: 'Գույք',
    caseType: 'Վաճառք',
    isPaid: true,
    price: 20000,
    payment_type: 'transfer',
    status: 'closed',
    closed_at: new Date('2024-10-01T00:00:00Z'),
    assignedEmployee: { connect: { id: 6 } }
  },
  {
    entryDate: new Date('2025-01-08T00:00:00Z'),
    entryNumber: '111-Վ/25',
    caseNumber: 'ԱՎԴ1/0011/01/25',
    judge: 'Ա. Սարգսյան',
    plaintiff: 'ԱրմՍտրոյԲանկ',
    defendant: 'Անահիտ Սեդրակյան',
    investigatedAddress: 'Երևան, Արշակունյաց 22',
    propertyType: 'Բնակարան',
    caseType: 'Գրանցում',
    isPaid: true,
    price: 72000,
    payment_type: 'court',
    status: 'closed',
    closed_at: new Date('2025-02-14T00:00:00Z'),
    assignedEmployee: { connect: { id: 2 } }
  },
  {
    entryDate: new Date('2025-03-11T00:00:00Z'),
    entryNumber: '112-Վ/25',
    caseNumber: 'ԱՎԴ1/0012/03/25',
    judge: 'Լ. Հարությունյան',
    plaintiff: 'ՎՏԲ Հայաստան Բանկ',
    defendant: 'Գոռ Թորոսյան',
    investigatedAddress: 'Երևան, Սարյան 17',
    propertyType: 'Տուն',
    caseType: 'Գրանցում',
    isPaid: true,
    price: 140000,
    payment_type: 'transfer',
    status: 'closed',
    closed_at: new Date('2025-04-20T00:00:00Z'),
    assignedEmployee: { connect: { id: 3 } }
  },
  {
    entryDate: new Date('2025-05-09T00:00:00Z'),
    entryNumber: '113-Վ/25',
    caseNumber: 'ԱՎԴ1/0013/05/25',
    judge: 'Ս. Թորոսյան',
    plaintiff: 'Ինեկոբանկ',
    defendant: 'Լիլիթ Հովհաննիսյան',
    investigatedAddress: 'Երևան, Մ. Մաշտոցի 34',
    propertyType: 'Հողատարածք',
    caseType: 'Գրանցում',
    isPaid: true,
    price: 58000,
    payment_type: 'cash',
    status: 'closed',
    closed_at: new Date('2025-06-28T00:00:00Z'),
    assignedEmployee: { connect: { id: 4 } }
  },
  {
    entryDate: new Date('2025-07-15T00:00:00Z'),
    entryNumber: '114-Վ/25',
    caseNumber: 'ԱՎԴ1/0014/07/25',
    judge: 'Մ. Կարապետյան',
    plaintiff: 'Ազատություն Բանկ',
    defendant: 'Արամ Հովսեփյան',
    investigatedAddress: 'Երևան, Դավիթ Բեկ 21',
    propertyType: 'Ավտոմեքենա',
    caseType: 'Վաճառք',
    isPaid: true,
    price: 35000,
    payment_type: 'cash',
    status: 'closed',
    closed_at: new Date('2025-08-18T00:00:00Z'),
    assignedEmployee: { connect: { id: 5 } }
  },
  {
    entryDate: new Date('2025-09-03T00:00:00Z'),
    entryNumber: '115-Վ/25',
    caseNumber: 'ԱՎԴ1/0015/09/25',
    judge: 'Գ. Հովհաննիսյան',
    plaintiff: 'ԱրմՍտրոյԲանկ',
    defendant: 'Միքայել Սիմոնյան',
    investigatedAddress: 'Երևան, Նալբանդյան 55',
    propertyType: 'Գույք',
    caseType: 'Վաճառք',
    isPaid: true,
    price: 18000,
    payment_type: 'transfer',
    status: 'closed',
    closed_at: new Date('2025-10-01T00:00:00Z'),
    assignedEmployee: { connect: { id: 6 } }
  },
  // 10 more closed cases to make 30 closed
  {
    entryDate: new Date('2023-02-01T00:00:00Z'),
    entryNumber: '116-Վ/23',
    caseNumber: 'ԱՎԴ1/0016/02/23',
    judge: 'Ա. Սարգսյան',
    plaintiff: 'Ազատություն Բանկ',
    defendant: 'Անի Կարապետյան',
    investigatedAddress: 'Երևան, Սայաթ-Նովա 7',
    propertyType: 'Բնակարան',
    caseType: 'Գրանցում',
    isPaid: true,
    price: 67000,
    payment_type: 'transfer',
    status: 'closed',
    closed_at: new Date('2023-03-12T00:00:00Z'),
    assignedEmployee: { connect: { id: 2 } }
  },
  {
    entryDate: new Date('2023-04-05T00:00:00Z'),
    entryNumber: '117-Վ/23',
    caseNumber: 'ԱՎԴ1/0017/04/23',
    judge: 'Լ. Հարությունյան',
    plaintiff: 'ՎՏԲ Հայաստան Բանկ',
    defendant: 'Մարատ Ավետիսյան',
    investigatedAddress: 'Երևան, Խանջյան 12',
    propertyType: 'Տուն',
    caseType: 'Գրանցում',
    isPaid: true,
    price: 110000,
    payment_type: 'cash',
    status: 'closed',
    closed_at: new Date('2023-05-18T00:00:00Z'),
    assignedEmployee: { connect: { id: 3 } }
  },
  {
    entryDate: new Date('2023-06-12T00:00:00Z'),
    entryNumber: '118-Վ/23',
    caseNumber: 'ԱՎԴ1/0018/06/23',
    judge: 'Ս. Թորոսյան',
    plaintiff: 'ԱրմՍտրոյԲանկ',
    defendant: 'Գոռ Ղազարյան',
    investigatedAddress: 'Երևան, Աբովյան 45',
    propertyType: 'Հողատարածք',
    caseType: 'Գրանցում',
    isPaid: true,
    price: 47000,
    payment_type: 'transfer',
    status: 'closed',
    closed_at: new Date('2023-07-22T00:00:00Z'),
    assignedEmployee: { connect: { id: 4 } }
  },
  {
    entryDate: new Date('2023-08-20T00:00:00Z'),
    entryNumber: '119-Վ/23',
    caseNumber: 'ԱՎԴ1/0019/08/23',
    judge: 'Մ. Կարապետյան',
    plaintiff: 'Ինեկոբանկ',
    defendant: 'Հասմիկ Մարտիրոսյան',
    investigatedAddress: 'Երևան, Մաշտոց 50',
    propertyType: 'Ավտոմեքենա',
    caseType: 'Վաճառք',
    isPaid: true,
    price: 32000,
    payment_type: 'cash',
    status: 'closed',
    closed_at: new Date('2023-09-10T00:00:00Z'),
    assignedEmployee: { connect: { id: 5 } }
  },
  {
    entryDate: new Date('2023-10-05T00:00:00Z'),
    entryNumber: '120-Վ/23',
    caseNumber: 'ԱՎԴ1/0020/10/23',
    judge: 'Գ. Հովհաննիսյան',
    plaintiff: 'Ազատություն Բանկ',
    defendant: 'Աննա Հակոբյան',
    investigatedAddress: 'Երևան, Բաղրամյան 20',
    propertyType: 'Գույք',
    caseType: 'Վաճառք',
    isPaid: true,
    price: 16000,
    payment_type: 'transfer',
    status: 'closed',
    closed_at: new Date('2023-11-01T00:00:00Z'),
    assignedEmployee: { connect: { id: 6 } }
  },
  // 5 canceled cases
  {
    entryDate: new Date('2024-01-15T00:00:00Z'),
    entryNumber: '121-Վ/24',
    caseNumber: 'ԱՎԴ1/0021/01/24',
    judge: 'Ա. Սարգսյան',
    plaintiff: 'ԱրմՍտրոյԲանկ',
    defendant: 'Արամ Գևորգյան',
    investigatedAddress: 'Երևան, Մաշտոցի 100',
    propertyType: 'Բնակարան',
    caseType: 'Գրանցում',
    isPaid: false,
    price: 0,
    payment_type: 'for_free',
    status: 'canceled',
    assignedEmployee: { connect: { id: 2 } }
  },
  {
    entryDate: new Date('2024-03-20T00:00:00Z'),
    entryNumber: '122-Վ/24',
    caseNumber: 'ԱՎԴ1/0022/03/24',
    judge: 'Լ. Հարությունյան',
    plaintiff: 'ՎՏԲ Հայաստան Բանկ',
    defendant: 'Մարիամ Հովհաննիսյան',
    investigatedAddress: 'Երևան, Նալբանդյան 67',
    propertyType: 'Տուն',
    caseType: 'Վաճառք',
    isPaid: false,
    price: 0,
    payment_type: 'for_free',
    status: 'canceled',
    assignedEmployee: { connect: { id: 3 } }
  },
  {
    entryDate: new Date('2024-05-10T00:00:00Z'),
    entryNumber: '123-Վ/24',
    caseNumber: 'ԱՎԴ1/0023/05/24',
    judge: 'Ս. Թորոսյան',
    plaintiff: 'Ազատություն Բանկ',
    defendant: 'Հրաչ Մելիքյան',
    investigatedAddress: 'Երևան, Խանջյան 33',
    propertyType: 'Գույք',
    caseType: 'Վաճառք',
    isPaid: false,
    price: 0,
    payment_type: 'for_free',
    status: 'canceled',
    assignedEmployee: { connect: { id: 4 } }
  },
  {
    entryDate: new Date('2025-01-05T00:00:00Z'),
    entryNumber: '124-Վ/25',
    caseNumber: 'ԱՎԴ1/0024/01/25',
    judge: 'Մ. Կարապետյան',
    plaintiff: 'Ինեկոբանկ',
    defendant: 'Արփինե Սարգսյան',
    investigatedAddress: 'Երևան, Աբովյան 77',
    propertyType: 'Բնակարան',
    caseType: 'Գրանցում',
    isPaid: false,
    price: 0,
    payment_type: 'for_free',
    status: 'canceled',
    assignedEmployee: { connect: { id: 5 } }
  },
  {
    entryDate: new Date('2025-02-14T00:00:00Z'),
    entryNumber: '125-Վ/25',
    caseNumber: 'ԱՎԴ1/0025/02/25',
    judge: 'Գ. Հովհաննիսյան',
    plaintiff: 'ԱրմՍտրոյԲանկ',
    defendant: 'Անի Հովսեփյան',
    investigatedAddress: 'Երևան, Սայաթ-Նովա 29',
    propertyType: 'Տուն',
    caseType: 'Վաճառք',
    isPaid: false,
    price: 0,
    payment_type: 'for_free',
    status: 'canceled',
    assignedEmployee: { connect: { id: 6 } }
  },
  // 5 cases with waiting, in_progress, or completed
  {
    entryDate: new Date('2025-03-01T00:00:00Z'),
    entryNumber: '126-Վ/25',
    caseNumber: 'ԱՎԴ1/0026/03/25',
    judge: 'Ա. Սարգսյան',
    plaintiff: 'Ազատություն Բանկ',
    defendant: 'Գոռ Հարությունյան',
    investigatedAddress: 'Երևան, Բաղրամյան 54',
    propertyType: 'Բնակարան',
    caseType: 'Գրանցում',
    isPaid: false,
    price: 0,
    payment_type: 'cash',
    status: 'waiting',
    assignedEmployee: { connect: { id: 2 } }
  },
  {
    entryDate: new Date('2025-03-10T00:00:00Z'),
    entryNumber: '127-Վ/25',
    caseNumber: 'ԱՎԴ1/0027/03/25',
    judge: 'Լ. Հարությունյան',
    plaintiff: 'ՎՏԲ Հայաստան Բանկ',
    defendant: 'Մարիամ Սիմոնյան',
    investigatedAddress: 'Երևան, Մաշտոցի 28',
    propertyType: 'Տուն',
    caseType: 'Գրանցում',
    isPaid: false,
    price: 0,
    payment_type: 'transfer',
    status: 'in_progress',
    assignedEmployee: { connect: { id: 3 } }
  },
  {
    entryDate: new Date('2025-03-15T00:00:00Z'),
    entryNumber: '128-Վ/25',
    caseNumber: 'ԱՎԴ1/0028/03/25',
    judge: 'Ս. Թորոսյան',
    plaintiff: 'Ազատություն Բանկ',
    defendant: 'Արամ Մարտիրոսյան',
    investigatedAddress: 'Երևան, Խանջյան 9',
    propertyType: 'Հողատարածք',
    caseType: 'Գրանցում',
    isPaid: false,
    price: 0,
    payment_type: 'cash',
    status: 'completed',
    assignedEmployee: { connect: { id: 4 } }
  },
  {
    entryDate: new Date('2025-03-20T00:00:00Z'),
    entryNumber: '129-Վ/25',
    caseNumber: 'ԱՎԴ1/0029/03/25',
    judge: 'Մ. Կարապետյան',
    plaintiff: 'Ինեկոբանկ',
    defendant: 'Հասմիկ Սարգսյան',
    investigatedAddress: 'Երևան, Աբովյան 12',
    propertyType: 'Ավտոմեքենա',
    caseType: 'Վաճառք',
    isPaid: false,
    price: 0,
    payment_type: 'cash',
    status: 'waiting',
    assignedEmployee: { connect: { id: 5 } }
  },
  {
    entryDate: new Date('2025-03-25T00:00:00Z'),
    entryNumber: '130-Վ/25',
    caseNumber: 'ԱՎԴ1/0030/03/25',
    judge: 'Գ. Հովհաննիսյան',
    plaintiff: 'Ազատություն Բանկ',
    defendant: 'Արփինե Հովհաննիսյան',
    investigatedAddress: 'Երևան, Սարյան 55',
    propertyType: 'Գույք',
    caseType: 'Վաճառք',
    isPaid: false,
    price: 0,
    payment_type: 'transfer',
    status: 'in_progress',
    assignedEmployee: { connect: { id: 6 } }
  }
];

module.exports = cases;
