const casesData = [
    {
      entryDate: new Date('2023-01-05T00:00:00Z'),
      entryNumber: '101-Վ/23',
      caseNumber: 'ԱՎԴ1/0001/01/23',
      judge: 'Ա. Սարգսյան',
      plaintiff: 'ԱրմՍտրոյԲանկ',
      defendant: 'Գևորգ Մանուկյան',
      investigatedAddress: 'Երևան, Նալբանդյան 12',
      propertyType: 'Բնակարան',
      caseType: 'Գրանցում',
      isPaid: true,
      price: 65000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2023-02-18T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2023-02-10T00:00:00Z'),
      entryNumber: '102-Վ/23',
      caseNumber: 'ԱՎԴ1/0002/02/23',
      judge: 'Գ. Հարությունյան',
      plaintiff: 'ՀայԷկոնոմԲանկ',
      defendant: 'Արսեն Գրիգորյան',
      investigatedAddress: 'Արարատի մարզ, Սասունի փողոց 26',
      propertyType: 'Հողամաս',
      caseType: 'Չափագրում',
      isPaid: true,
      price: 80000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2023-03-01T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2023-03-05T00:00:00Z'),
      entryNumber: '103-Վ/23',
      caseNumber: 'ԱՎԴ1/0003/03/23',
      judge: 'Մ. Պետրոսյան',
      plaintiff: 'Արամ Խաչատրյան',
      defendant: 'Աննա Սարգսյան',
      investigatedAddress: 'Գյումրի, Սպենդիարյան 5',
      propertyType: 'Տուն',
      caseType: 'Սեփականության վեճ',
      isPaid: true,
      price: 120000,
      payment_type: 'cash',
      status: 'closed',
      closed_at: new Date('2023-04-10T00:00:00Z'),
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2023-04-01T00:00:00Z'),
      entryNumber: '104-Վ/23',
      caseNumber: 'ԱՎԴ1/0004/04/23',
      judge: 'Ն. Հովսեփյան',
      plaintiff: 'ՎՏԲ Բանկ',
      defendant: 'Սոսե Դանիելյան',
      investigatedAddress: 'Երևան, Աբովյան 87',
      propertyType: 'Բնակարան',
      caseType: 'Հիպոտեկային վեճ',
      isPaid: true,
      price: 95000,
      payment_type: 'court',
      status: 'closed',
      closed_at: new Date('2023-05-15T00:00:00Z'),
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2023-05-10T00:00:00Z'),
      entryNumber: '105-Վ/23',
      caseNumber: 'ԱՎԴ1/0005/05/23',
      judge: 'Հ. Կարապետյան',
      plaintiff: 'Կոմերցբանկ Արմենիա',
      defendant: 'Տիգրան Հակոբյան',
      investigatedAddress: 'Աբովյան, Հանրապետության 22',
      propertyType: 'Կոմերցիոն տարածք',
      caseType: 'Գույքային վեճ',
      isPaid: true,
      price: 135000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2023-06-12T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2023-06-05T00:00:00Z'),
      entryNumber: '106-Վ/23',
      caseNumber: 'ԱՎԴ1/0006/06/23',
      judge: 'Գ. Հարությունյան',
      plaintiff: 'ՀայԷկոնոմԲանկ',
      defendant: 'Արսեն Գրիգորյան',
      investigatedAddress: 'Արարատի մարզ, Սասունի փողոց 26',
      propertyType: 'Հող, Համալիր',
      caseType: 'Չափագրում',
      isPaid: false,
      price: 80000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2023-07-01T00:00:00Z'),
      assignedEmployee: { connect: { id: 4 } },
    },
    {
      entryDate: new Date('2023-07-01T00:00:00Z'),
      entryNumber: '107-Վ/23',
      caseNumber: 'ԱՎԴ1/0007/07/23',
      judge: 'Ա. Սահակյան',
      plaintiff: 'Արտաշես Մկրտչյան',
      defendant: 'Լուսինե Թովմասյան',
      investigatedAddress: 'Երևան, Տերյան 50',
      propertyType: 'Բնակարան',
      caseType: 'Հարևանային վեճ',
      isPaid: true,
      price: 40000,
      payment_type: 'cash',
      status: 'closed',
      closed_at: new Date('2023-08-10T00:00:00Z'),
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2023-08-05T00:00:00Z'),
      entryNumber: '108-Վ/23',
      caseNumber: 'ԱՎԴ1/0008/08/23',
      judge: 'Գ. Մարգարյան',
      plaintiff: 'Արամ Բաբայան',
      defendant: 'Մանե Ավետիսյան',
      investigatedAddress: 'Արմավիր, Շիրակի 19',
      propertyType: 'Տուն',
      caseType: 'Սեփականության գրանցում',
      isPaid: true,
      price: 90000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2023-09-12T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2023-09-10T00:00:00Z'),
      entryNumber: '109-Վ/23',
      caseNumber: 'ԱՎԴ1/0009/09/23',
      judge: 'Ա. Հակոբյան',
      plaintiff: 'ԱրմՍտրոյԲանկ',
      defendant: 'Գոհար Սահակյան',
      investigatedAddress: 'Երևան, Բաղրամյան 17',
      propertyType: 'Բնակարան',
      caseType: 'Փոխանցման վեճ',
      isPaid: false,
      price: 70000,
      payment_type: 'for_free',
      status: 'closed',
      closed_at: new Date('2023-10-01T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },

    // ===== CLOSED CASES 2024 =====
    {
      entryDate: new Date('2024-01-05T00:00:00Z'),
      entryNumber: '110-Վ/24',
      caseNumber: 'ԱՎԴ1/0010/01/24',
      judge: 'Մ. Հովհաննիսյան',
      plaintiff: 'Անի Թորոսյան',
      defendant: 'Արման Հարությունյան',
      investigatedAddress: 'Երևան, Արգիշտի 2',
      propertyType: 'Բնակարան',
      caseType: 'Սեփականության փոխանցում',
      isPaid: true,
      price: 56000,
      payment_type: 'cash',
      status: 'closed',
      closed_at: new Date('2024-02-15T00:00:00Z'),
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2024-02-12T00:00:00Z'),
      entryNumber: '111-Վ/24',
      caseNumber: 'ԱՎԴ1/0011/02/24',
      judge: 'Հ. Հովհաննիսյան',
      plaintiff: 'ԱրմՏեք',
      defendant: 'Սեդրակ Մկրտչյան',
      investigatedAddress: 'Գյումրի, Հալաբյան 3',
      propertyType: 'Կոմերցիոն տարածք',
      caseType: 'Գույքային վեճ',
      isPaid: true,
      price: 78000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2024-03-20T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2024-03-10T00:00:00Z'),
      entryNumber: '112-Վ/24',
      caseNumber: 'ԱՎԴ1/0012/03/24',
      judge: 'Ն. Սարգսյան',
      plaintiff: 'ՀայԱգրոբանկ',
      defendant: 'Էմիլիա Մարտիրոսյան',
      investigatedAddress: 'Երևան, Նար-Դոսի 25',
      propertyType: 'Տուն',
      caseType: 'Հարևանային վեճ',
      isPaid: true,
      price: 88000,
      payment_type: 'cash',
      status: 'closed',
      closed_at: new Date('2024-04-18T00:00:00Z'),
      assignedEmployee: { connect: { id: 5 } },
    },
    {
      entryDate: new Date('2024-04-08T00:00:00Z'),
      entryNumber: '113-Վ/24',
      caseNumber: 'ԱՎԴ1/0013/04/24',
      judge: 'Ա. Մանուկյան',
      plaintiff: 'ՎՏԲ Բանկ',
      defendant: 'Լևոն Սարգսյան',
      investigatedAddress: 'Երևան, Մաշտոցի 45',
      propertyType: 'Բնակարան',
      caseType: 'Հիպոտեկային վեճ',
      isPaid: true,
      price: 94000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2024-05-22T00:00:00Z'),
      assignedEmployee: { connect: { id: 4 } },
    },
    {
      entryDate: new Date('2024-05-15T00:00:00Z'),
      entryNumber: '114-Վ/24',
      caseNumber: 'ԱՎԴ1/0014/05/24',
      judge: 'Մ. Հակոբյան',
      plaintiff: 'Արտաշես Մկրտչյան',
      defendant: 'Լուսինե Թովմասյան',
      investigatedAddress: 'Երևան, Տերյան 50',
      propertyType: 'Բնակարան',
      caseType: 'Սեփականության վեճ',
      isPaid: true,
      price: 72000,
      payment_type: 'cash',
      status: 'closed',
      closed_at: new Date('2024-06-28T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2024-06-10T00:00:00Z'),
      entryNumber: '115-Վ/24',
      caseNumber: 'ԱՎԴ1/0015/06/24',
      judge: 'Ա. Սարգսյան',
      plaintiff: 'ՀայԷկոնոմԲանկ',
      defendant: 'Արսեն Գրիգորյան',
      investigatedAddress: 'Արարատի մարզ, Սասունի փողոց 26',
      propertyType: 'Հողամաս',
      caseType: 'Չափագրում',
      isPaid: true,
      price: 81000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2024-07-15T00:00:00Z'),
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2024-07-05T00:00:00Z'),
      entryNumber: '116-Վ/24',
      caseNumber: 'ԱՎԴ1/0016/07/24',
      judge: 'Գ. Հարությունյան',
      plaintiff: 'Արամ Խաչատրյան',
      defendant: 'Աննա Սարգսյան',
      investigatedAddress: 'Գյումրի, Սպենդիարյան 5',
      propertyType: 'Տուն',
      caseType: 'Սեփականության փոխանցում',
      isPaid: true,
      price: 92000,
      payment_type: 'cash',
      status: 'closed',
      closed_at: new Date('2024-08-20T00:00:00Z'),
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2024-08-12T00:00:00Z'),
      entryNumber: '117-Վ/24',
      caseNumber: 'ԱՎԴ1/0017/08/24',
      judge: 'Ն. Հովսեփյան',
      plaintiff: 'Կոմերցբանկ Արմենիա',
      defendant: 'Տիգրան Հակոբյան',
      investigatedAddress: 'Աբովյան, Հանրապետության 22',
      propertyType: 'Կոմերցիոն տարածք',
      caseType: 'Գույքային վեճ',
      isPaid: true,
      price: 135000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2024-09-18T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2024-09-05T00:00:00Z'),
      entryNumber: '118-Վ/24',
      caseNumber: 'ԱՎԴ1/0018/09/24',
      judge: 'Ա. Սահակյան',
      plaintiff: 'Արտաշես Մկրտչյան',
      defendant: 'Լուսինե Թովմասյան',
      investigatedAddress: 'Երևան, Տերյան 50',
      propertyType: 'Բնակարան',
      caseType: 'Հարևանային վեճ',
      isPaid: true,
      price: 41000,
      payment_type: 'cash',
      status: 'closed',
      closed_at: new Date('2024-10-10T00:00:00Z'),
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2024-10-01T00:00:00Z'),
      entryNumber: '119-Վ/24',
      caseNumber: 'ԱՎԴ1/0019/10/24',
      judge: 'Գ. Մարգարյան',
      plaintiff: 'Արամ Բաբայան',
      defendant: 'Մանե Ավետիսյան',
      investigatedAddress: 'Արմավիր, Շիրակի 19',
      propertyType: 'Տուն',
      caseType: 'Սեփականության գրանցում',
      isPaid: true,
      price: 91000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2024-11-15T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },

    // ===== CLOSED CASES 2025 =====
    {
      entryDate: new Date('2025-01-05T00:00:00Z'),
      entryNumber: '120-Վ/25',
      caseNumber: 'ԱՎԴ1/0020/01/25',
      judge: 'Ա. Սարգսյան',
      plaintiff: 'ԱրմՍտրոյԲանկ',
      defendant: 'Գևորգ Մանուկյան',
      investigatedAddress: 'Երևան, Նալբանդյան 12',
      propertyType: 'Բնակարան',
      caseType: 'Գրանցում',
      isPaid: true,
      price: 67000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2025-02-18T00:00:00Z'),
      assignedEmployee: { connect: { id: 4 } },
    },
    {
      entryDate: new Date('2025-02-10T00:00:00Z'),
      entryNumber: '121-Վ/25',
      caseNumber: 'ԱՎԴ1/0021/02/25',
      judge: 'Գ. Հարությունյան',
      plaintiff: 'ՀայԷկոնոմԲանկ',
      defendant: 'Արսեն Գրիգորյան',
      investigatedAddress: 'Արարատի մարզ, Սասունի փողոց 26',
      propertyType: 'Հողամաս',
      caseType: 'Չափագրում',
      isPaid: true,
      price: 81000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2025-03-01T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2025-03-05T00:00:00Z'),
      entryNumber: '122-Վ/25',
      caseNumber: 'ԱՎԴ1/0022/03/25',
      judge: 'Մ. Պետրոսյան',
      plaintiff: 'Արամ Խաչատրյան',
      defendant: 'Աննա Սարգսյան',
      investigatedAddress: 'Գյումրի, Սպենդիարյան 5',
      propertyType: 'Տուն',
      caseType: 'Սեփականության վեճ',
      isPaid: true,
      price: 123000,
      payment_type: 'cash',
      status: 'closed',
      closed_at: new Date('2025-04-10T00:00:00Z'),
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2025-04-01T00:00:00Z'),
      entryNumber: '123-Վ/25',
      caseNumber: 'ԱՎԴ1/0023/04/25',
      judge: 'Ն. Հովսեփյան',
      plaintiff: 'ՎՏԲ Բանկ',
      defendant: 'Սոսե Դանիելյան',
      investigatedAddress: 'Երևան, Աբովյան 87',
      propertyType: 'Բնակարան',
      caseType: 'Հիպոտեկային վեճ',
      isPaid: true,
      price: 97000,
      payment_type: 'court',
      status: 'closed',
      closed_at: new Date('2025-05-15T00:00:00Z'),
      assignedEmployee: { connect: { id: 5 } },
    },
    {
      entryDate: new Date('2025-05-10T00:00:00Z'),
      entryNumber: '124-Վ/25',
      caseNumber: 'ԱՎԴ1/0024/05/25',
      judge: 'Հ. Կարապետյան',
      plaintiff: 'Կոմերցբանկ Արմենիա',
      defendant: 'Տիգրան Հակոբյան',
      investigatedAddress: 'Աբովյան, Հանրապետության 22',
      propertyType: 'Կոմերցիոն տարածք',
      caseType: 'Գույքային վեճ',
      isPaid: true,
      price: 138000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2025-06-12T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2025-06-05T00:00:00Z'),
      entryNumber: '125-Վ/25',
      caseNumber: 'ԱՎԴ1/0025/06/25',
      judge: 'Գ. Հարությունյան',
      plaintiff: 'ՀայԷկոնոմԲանկ',
      defendant: 'Արսեն Գրիգորյան',
      investigatedAddress: 'Արարատի մարզ, Սասունի փողոց 26',
      propertyType: 'Հող, Համալիր',
      caseType: 'Չափագրում',
      isPaid: false,
      price: 81000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2025-07-01T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2025-07-01T00:00:00Z'),
      entryNumber: '126-Վ/25',
      caseNumber: 'ԱՎԴ1/0026/07/25',
      judge: 'Ա. Սահակյան',
      plaintiff: 'Արտաշես Մկրտչյան',
      defendant: 'Լուսինե Թովմասյան',
      investigatedAddress: 'Երևան, Տերյան 50',
      propertyType: 'Բնակարան',
      caseType: 'Հարևանային վեճ',
      isPaid: true,
      price: 43000,
      payment_type: 'cash',
      status: 'closed',
      closed_at: new Date('2025-08-10T00:00:00Z'),
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2025-08-05T00:00:00Z'),
      entryNumber: '127-Վ/25',
      caseNumber: 'ԱՎԴ1/0027/08/25',
      judge: 'Գ. Մարգարյան',
      plaintiff: 'Արամ Բաբայան',
      defendant: 'Մանե Ավետիսյան',
      investigatedAddress: 'Արմավիր, Շիրակի 19',
      propertyType: 'Տուն',
      caseType: 'Սեփականության գրանցում',
      isPaid: true,
      price: 91000,
      payment_type: 'transfer',
      status: 'closed',
      closed_at: new Date('2025-09-12T00:00:00Z'),
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2025-09-05T00:00:00Z'),
      entryNumber: '128-Վ/25',
      caseNumber: 'ԱՎԴ1/0028/09/25',
      judge: 'Ա. Հակոբյան',
      plaintiff: 'ԱրմՍտրոյԲանկ',
      defendant: 'Գոհար Սահակյան',
      investigatedAddress: 'Երևան, Բաղրամյան 17',
      propertyType: 'Բնակարան',
      caseType: 'Փոխանցման վեճ',
      isPaid: false,
      price: 71000,
      payment_type: 'for_free',
      status: 'closed',
      closed_at: new Date('2025-10-01T00:00:00Z'),
      assignedEmployee: { connect: { id: 3 } },
    },

    // ===== OPEN CASES 2025 =====
    {
      entryDate: new Date('2025-09-20T00:00:00Z'),
      entryNumber: '129-Վ/25',
      caseNumber: 'ԱՎԴ1/0029/09/25',
      judge: 'Ն. Սարգսյան',
      plaintiff: 'ՎՏԲ Բանկ',
      defendant: 'Սոսե Դանիելյան',
      investigatedAddress: 'Երևան, Աբովյան 87',
      propertyType: 'Բնակարան',
      caseType: 'Հիպոտեկային վեճ',
      isPaid: false,
      price: 96000,
      payment_type: 'court',
      status: 'waiting',
      closed_at: null,
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2025-09-22T00:00:00Z'),
      entryNumber: '130-Վ/25',
      caseNumber: 'ԱՎԴ1/0030/09/25',
      judge: 'Ա. Մանուկյան',
      plaintiff: 'Կոմերցբանկ Արմենիա',
      defendant: 'Տիգրան Հակոբյան',
      investigatedAddress: 'Աբովյան, Հանրապետության 22',
      propertyType: 'Կոմերցիոն տարածք',
      caseType: 'Գույքային վեճ',
      isPaid: false,
      price: 138500,
      payment_type: 'transfer',
      status: 'in_progress',
      closed_at: null,
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2025-09-25T00:00:00Z'),
      entryNumber: '131-Վ/25',
      caseNumber: 'ԱՎԴ1/0031/09/25',
      judge: 'Մ. Հակոբյան',
      plaintiff: 'Արամ Խաչատրյան',
      defendant: 'Աննա Սարգսյան',
      investigatedAddress: 'Գյումրի, Սպենդիարյան 5',
      propertyType: 'Տուն',
      caseType: 'Սեփականության փոխանցում',
      isPaid: false,
      price: 124000,
      payment_type: 'cash',
      status: 'completed',
      closed_at: null,
      assignedEmployee: { connect: { id: 4 } },
    },
    {
      entryDate: new Date('2025-09-27T00:00:00Z'),
      entryNumber: '132-Վ/25',
      caseNumber: 'ԱՎԴ1/0032/09/25',
      judge: 'Ա. Սարգսյան',
      plaintiff: 'ՀայԷկոնոմԲանկ',
      defendant: 'Արսեն Գրիգորյան',
      investigatedAddress: 'Արարատի մարզ, Սասունի փողոց 26',
      propertyType: 'Հող, Համալիր',
      caseType: 'Չափագրում',
      isPaid: false,
      price: 81000,
      payment_type: 'transfer',
      status: 'canceled',
      closed_at: null,
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2025-09-29T00:00:00Z'),
      entryNumber: '133-Վ/25',
      caseNumber: 'ԱՎԴ1/0033/09/25',
      judge: 'Գ. Հարությունյան',
      plaintiff: 'Արամ Բաբայան',
      defendant: 'Մանե Ավետիսյան',
      investigatedAddress: 'Արմավիր, Շիրակի 19',
      propertyType: 'Տուն',
      caseType: 'Սեփականության գրանցում',
      isPaid: false,
      price: 91000,
      payment_type: 'transfer',
      status: 'waiting',
      closed_at: null,
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2025-10-01T00:00:00Z'),
      entryNumber: '134-Վ/25',
      caseNumber: 'ԱՎԴ1/0034/10/25',
      judge: 'Ն. Հովսեփյան',
      plaintiff: 'ՎՏԲ Բանկ',
      defendant: 'Սոսե Դանիելյան',
      investigatedAddress: 'Երևան, Աբովյան 87',
      propertyType: 'Բնակարան',
      caseType: 'Հիպոտեկային վեճ',
      isPaid: false,
      price: 96000,
      payment_type: 'court',
      status: 'in_progress',
      closed_at: null,
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2025-10-03T00:00:00Z'),
      entryNumber: '135-Վ/25',
      caseNumber: 'ԱՎԴ1/0035/10/25',
      judge: 'Ա. Մանուկյան',
      plaintiff: 'Կոմերցբանկ Արմենիա',
      defendant: 'Տիգրան Հակոբյան',
      investigatedAddress: 'Աբովյան, Հանրապետության 22',
      propertyType: 'Կոմերցիոն տարածք',
      caseType: 'Գույքային վեճ',
      isPaid: false,
      price: 138500,
      payment_type: 'transfer',
      status: 'completed',
      closed_at: null,
      assignedEmployee: { connect: { id: 4 } },
    },
    {
      entryDate: new Date('2025-10-05T00:00:00Z'),
      entryNumber: '136-Վ/25',
      caseNumber: 'ԱՎԴ1/0036/10/25',
      judge: 'Մ. Հակոբյան',
      plaintiff: 'Արամ Խաչատրյան',
      defendant: 'Աննա Սարգսյան',
      investigatedAddress: 'Գյումրի, Սպենդիարյան 5',
      propertyType: 'Տուն',
      caseType: 'Սեփականության փոխանցում',
      isPaid: false,
      price: 124000,
      payment_type: 'cash',
      status: 'canceled',
      closed_at: null,
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2025-10-07T00:00:00Z'),
      entryNumber: '137-Վ/25',
      caseNumber: 'ԱՎԴ1/0037/10/25',
      judge: 'Ա. Սարգսյան',
      plaintiff: 'ՀայԷկոնոմԲանկ',
      defendant: 'Արսեն Գրիգորյան',
      investigatedAddress: 'Արարատի մարզ, Սասունի փողոց 26',
      propertyType: 'Հող, Համալիր',
      caseType: 'Չափագրում',
      isPaid: false,
      price: 81000,
      payment_type: 'transfer',
      status: 'waiting',
      closed_at: null,
      assignedEmployee: { connect: { id: 2 } },
    },
    {
      entryDate: new Date('2025-10-09T00:00:00Z'),
      entryNumber: '138-Վ/25',
      caseNumber: 'ԱՎԴ1/0038/10/25',
      judge: 'Գ. Հարությունյան',
      plaintiff: 'Արամ Բաբայան',
      defendant: 'Մանե Ավետիսյան',
      investigatedAddress: 'Արմավիր, Շիրակի 19',
      propertyType: 'Տուն',
      caseType: 'Սեփականության գրանցում',
      isPaid: false,
      price: 91000,
      payment_type: 'transfer',
      status: 'in_progress',
      closed_at: null,
      assignedEmployee: { connect: { id: 3 } },
    },
    {
      entryDate: new Date('2025-10-10T00:00:00Z'),
      entryNumber: '139-Վ/25',
      caseNumber: 'ԱՎԴ1/0039/10/25',
      judge: 'Ն. Հովսեփյան',
      plaintiff: 'ՎՏԲ Բանկ',
      defendant: 'Սոսե Դանիելյան',
      investigatedAddress: 'Երևան, Աբովյան 87',
      propertyType: 'Բնակարան',
      caseType: 'Հիպոտեկային վեճ',
      isPaid: false,
      price: 96000,
      payment_type: 'court',
      status: 'completed',
      closed_at: null,
      assignedEmployee: { connect: { id: 4 } },
    },
    {
      entryDate: new Date('2025-10-12T00:00:00Z'),
      entryNumber: '140-Վ/25',
      caseNumber: 'ԱՎԴ1/0040/10/25',
      judge: 'Ա. Մանուկյան',
      plaintiff: 'Կոմերցբանկ Արմենիա',
      defendant: 'Տիգրան Հակոբյան',
      investigatedAddress: 'Աբովյան, Հանրապետության 22',
      propertyType: 'Կոմերցիոն տարածք',
      caseType: 'Գույքային վեճ',
      isPaid: false,
      price: 138500,
      payment_type: 'transfer',
      status: 'waiting',
      closed_at: null,
      assignedEmployee: { connect: { id: 4 } },
    },
  ];

  export default casesData